language: csharp
solution: PreventReboot.sln

sudo: required
dist: trusty

install:
  - nuget restore PreventReboot.sln
  - cp ./MSBuild.ILMerge.Task.targets ./packages/MSBuild.ILMerge.Task.1.0.5/build/MSBuild.ILMerge.Task.targets

