language: csharp
solution: PreventReboot.sln

sudo: required
dist: trusty

install:
  - nuget restore PreventReboot.sln

  - patch -p1 /home/travis/build/jakenjarvis/PreventReboot/packages/MSBuild.ILMerge.Task.1.0.5/build/MSBuild.ILMerge.Task.targets < ./MSBuild.ILMerge.Task.targets-1.0.5.patch

