language: csharp
solution: PreventReboot.sln

install:
  - nuget install MSBuild.ILMerge.Task -Version 1.0.5
  - patch /home/travis/build/jakenjarvis/PreventReboot/packages/MSBuild.ILMerge.Task.1.0.5/build/MSBuild.ILMerge.Task.targets ./MSBuild.ILMerge.Task.targets_1.0.5.patch

  - nuget restore PreventReboot.sln

