language: csharp
solution: PreventReboot.sln

sudo: required
dist: trusty

install:
  - nuget install ILMerge -Version 2.14.1208 -ExcludeVersion -OutputDirectory ./packages
  - nuget restore PreventReboot.sln
  - cp -f ./MSBuild.ILMerge.Task.targets ./packages/MSBuild.ILMerge.Task.1.0.5/build/MSBuild.ILMerge.Task.targets

  - cat /home/travis/build/jakenjarvis/PreventReboot/packages/MSBuild.ILMerge.Task.1.0.5/build/MSBuild.ILMerge.Task.targets

