version: '{build}'

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      GENERATOR: "Visual Studio 15 2017"

configuration:
  - Debug
  - Release

before_build:
  - nuget restore PreventReboot.sln

build:
  project: PreventReboot.sln

test_script:

after_test:

