init:
  - ps: |
      echo "$env:APPVEYOR_REPO_TAG_NAME"
      $defVersion = "$env:APPVEYOR_REPO_TAG_NAME" -replace "[v]?(\d{1,}[.]\d{1,}[.]\d{1,})([.]\d{1,})?","`$1"
      echo "$defVersion"

      $defAssemblyVersion = $defVersion + "." + "$env:APPVEYOR_BUILD_NUMBER"
      echo "$defAssemblyVersion"
      Update-AppveyorBuild -Version "$defAssemblyVersion"

      $informationalVersion = "$($env:APPVEYOR_REPO_BRANCH)-$($env:APPVEYOR_REPO_COMMIT.substring(0,7))"
      echo "$informationalVersion"

      $artifactZipName = "PreventReboot-$($env:APPVEYOR_BUILD_VERSION)-$($informationalVersion)-$($env:CONFIGURATION).zip"
      echo "$artifactZipName"

version: '{build}'

skip_non_tags: true

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}-{$informationalVersion}"

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      GENERATOR: "Visual Studio 16 2019"

configuration:
  #- Debug
  - Release

before_build:
  - nuget restore PreventReboot.sln

build:
  project: PreventReboot.sln

after_build:
  - ps: mkdir publish
  - ps: copy "PreventReboot\bin\$($env:CONFIGURATION)\PreventReboot.exe" publish
  - ps: 7z a -tzip "$artifactZipName" ".\publish\*"

before_test:

test_script:

after_test:


artifacts:
  - path: PreventReboot-*.zip

before_deploy:

deploy:
  - provider: GitHub
    auth_token:
      secure: kCCkxLoVdy73Sxdyyl+5XxS72cvKFw/oOOfIs+GFIL1Pj7wtmFvNUETXxAofgwxT

    #release: $(APPVEYOR_BUILD_VERSION)
    description: It was automatically deployed by AppVeyor CI.

    draft: false
    prerelease: false
    force_update: true

    on:
      branch: master
      appveyor_repo_tag: true

after_deploy:

