init:
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
      }
      else
      {
        Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_BRANCH)-$($env:APPVEYOR_REPO_COMMIT.substring(0,7))"
      }

version: '{build}'

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      GENERATOR: "Visual Studio 15 2017"

configuration:
  - Debug
  - Release

before_build:
  - nuget restore PreventReboot.sln

build:
  project: PreventReboot.sln

after_build:

before_test:

test_script:

after_test:


artifacts:
  - path: PreventReboot\bin\$(CONFIGURATION)\PreventReboot.exe
    name: 'PreventReboot-$($env:VERSION).zip'


before_deploy:

deploy:
  - provider: GitHub
    release: 'PreventReboot-$($env:VERSION)'
    force_update: true

    on:
      #branch: master
      appveyor_repo_tag: true

    auth_token:
      secure: xDUB9jmTodzcvy1twsTYQ8RtANSfUvcFyOfc8df0ut/nwFdiWWS4hlOBqnxz8J/3

after_deploy:

